name: farmelonn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  camera: ^0.11.1
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  geolocator: ^14.0.0
  http: ^1.3.0
  permission_handler: ^12.0.0+1
  pin_code_fields: ^8.0.1
  provider: ^6.1.4
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/melon.png
    - assets/logo.jpeg
    - assets/drone.jpeg
    - assets/pest.jpeg
    - assets/ferti.jpeg
    - assets/profit.jpeg

flutter_icons:
  android: true
  image_path: "assets/logo.jpeg"
